/**
 * Artifact Routes — CRUD for legal work products (motions, memos, contracts, etc.)
 *
 * Artifacts are professional legal documents generated by the agent system.
 * They are separate from chat messages and can be exported as Word/PDF.
 */

import { Router, Request, Response } from 'express';
import { supabaseAdmin } from '../config/supabase.js';
import { isValidUUID } from '../middleware/security.js';
import {
  generateWordDocument,
  generatePdfDocument,
  parseMarkdownToSections,
  ExportPayload,
} from '../services/exportService.js';

const router = Router();

// UUID validation for route params
router.param('artifactId', (req, res, next, value) => {
  if (!isValidUUID(value)) {
    return res.status(400).json({ error: 'Invalid artifactId: must be a valid UUID' });
  }
  next();
});

// ── GET /api/artifacts — List artifacts (optionally filtered by session or case) ──

router.get('/', async (req: Request, res: Response) => {
  try {
    const tenantId = (req as any).tenantId;
    const { session_id, case_id, limit } = req.query;

    let query = supabaseAdmin
      .from('artifacts')
      .select('id, title, document_type, format, metadata, session_id, case_id, created_at, updated_at')
      .eq('tenant_id', tenantId)
      .order('created_at', { ascending: false })
      .limit(Number(limit) || 50);

    if (session_id && isValidUUID(session_id as string)) {
      query = query.eq('session_id', session_id);
    }
    if (case_id && isValidUUID(case_id as string)) {
      query = query.eq('case_id', case_id);
    }

    const { data, error } = await query;
    if (error) throw error;

    res.json({ artifacts: data || [], count: data?.length || 0 });
  } catch (err) {
    console.error('List artifacts error:', err);
    res.status(500).json({ error: 'Failed to list artifacts' });
  }
});

// ── GET /api/artifacts/:artifactId — Get a single artifact with full content ──

router.get('/:artifactId', async (req: Request, res: Response) => {
  try {
    const tenantId = (req as any).tenantId;
    const { artifactId } = req.params;

    const { data, error } = await supabaseAdmin
      .from('artifacts')
      .select('*')
      .eq('id', artifactId)
      .eq('tenant_id', tenantId)
      .single();

    if (error || !data) {
      return res.status(404).json({ error: 'Artifact not found' });
    }

    res.json({ artifact: data });
  } catch (err) {
    console.error('Get artifact error:', err);
    res.status(500).json({ error: 'Failed to get artifact' });
  }
});

// ── POST /api/artifacts — Create a new artifact ──

router.post('/', async (req: Request, res: Response) => {
  try {
    const tenantId = (req as any).tenantId;
    const userId = (req as any).user?.id;
    const { title, document_type, format, content, metadata, session_id, case_id, message_id } = req.body;

    if (!title || !content) {
      return res.status(400).json({ error: 'title and content are required' });
    }

    const { data, error } = await supabaseAdmin
      .from('artifacts')
      .insert({
        tenant_id: tenantId,
        user_id: userId,
        title,
        document_type: document_type || 'other',
        format: format || 'markdown',
        content,
        metadata: metadata || {},
        session_id: session_id || null,
        case_id: case_id || null,
        message_id: message_id ? Number(message_id) : null,
      })
      .select()
      .single();

    if (error) throw error;

    res.status(201).json({ artifact: data });
  } catch (err) {
    console.error('Create artifact error:', err);
    res.status(500).json({ error: 'Failed to create artifact' });
  }
});

// ── PUT /api/artifacts/:artifactId — Update an artifact ──

router.put('/:artifactId', async (req: Request, res: Response) => {
  try {
    const tenantId = (req as any).tenantId;
    const userId = (req as any).user?.id;
    const { artifactId } = req.params;
    const { title, content, metadata } = req.body;

    const updates: Record<string, any> = {};
    if (title !== undefined) updates.title = title;
    if (content !== undefined) updates.content = content;
    if (metadata !== undefined) updates.metadata = metadata;

    if (Object.keys(updates).length === 0) {
      return res.status(400).json({ error: 'No fields to update' });
    }

    const { data, error } = await supabaseAdmin
      .from('artifacts')
      .update(updates)
      .eq('id', artifactId)
      .eq('tenant_id', tenantId)
      .eq('user_id', userId)
      .select()
      .single();

    if (error || !data) {
      return res.status(404).json({ error: 'Artifact not found or not owned by you' });
    }

    res.json({ artifact: data });
  } catch (err) {
    console.error('Update artifact error:', err);
    res.status(500).json({ error: 'Failed to update artifact' });
  }
});

// ── DELETE /api/artifacts/:artifactId — Delete an artifact ──

router.delete('/:artifactId', async (req: Request, res: Response) => {
  try {
    const tenantId = (req as any).tenantId;
    const userId = (req as any).user?.id;
    const { artifactId } = req.params;

    const { error } = await supabaseAdmin
      .from('artifacts')
      .delete()
      .eq('id', artifactId)
      .eq('tenant_id', tenantId)
      .eq('user_id', userId);

    if (error) throw error;

    res.json({ success: true });
  } catch (err) {
    console.error('Delete artifact error:', err);
    res.status(500).json({ error: 'Failed to delete artifact' });
  }
});

// ── POST /api/artifacts/:artifactId/export — Export artifact as Word or PDF ──

router.post('/:artifactId/export', async (req: Request, res: Response) => {
  try {
    const tenantId = (req as any).tenantId;
    const { artifactId } = req.params;
    const { format } = req.body;

    if (!format || (format !== 'word' && format !== 'pdf')) {
      return res.status(400).json({ error: 'format must be "word" or "pdf"' });
    }

    // Fetch artifact
    const { data: artifact, error } = await supabaseAdmin
      .from('artifacts')
      .select('*')
      .eq('id', artifactId)
      .eq('tenant_id', tenantId)
      .single();

    if (error || !artifact) {
      return res.status(404).json({ error: 'Artifact not found' });
    }

    // Build export payload from artifact content
    const sections = parseMarkdownToSections(artifact.content);
    const meta = artifact.metadata || {};

    // Document type-specific subtitle
    const docTypeLabels: Record<string, string> = {
      motion: 'Motion',
      memo: 'Memorandum of Law',
      brief: 'Legal Brief',
      letter: 'Correspondence',
      contract_draft: 'Draft Agreement',
      discovery_request: 'Discovery Request',
      deposition_outline: 'Deposition Outline',
      case_summary: 'Case Summary',
      legal_analysis: 'Legal Analysis',
      compliance_report: 'Compliance Report',
      settlement_agreement: 'Settlement Agreement',
    };
    const subtitle = docTypeLabels[artifact.document_type] || undefined;

    const payload: ExportPayload = {
      title: artifact.title,
      subtitle,
      sections,
      metadata: {
        matter: meta.court || meta.jurisdiction || undefined,
        caseNumber: meta.case_number || undefined,
        date: meta.document_date || new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' }),
        author: meta.author || undefined,
      },
    };

    if (format === 'word') {
      const buffer = await generateWordDocument(payload);
      const filename = `${artifact.title.replace(/[^a-zA-Z0-9 ]/g, '').slice(0, 60)}.docx`;
      res.setHeader('Content-Type', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document');
      res.setHeader('Content-Disposition', `attachment; filename="${filename}"`);
      return res.send(buffer);
    }

    const buffer = await generatePdfDocument(payload);
    const filename = `${artifact.title.replace(/[^a-zA-Z0-9 ]/g, '').slice(0, 60)}.pdf`;
    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', `attachment; filename="${filename}"`);
    res.send(buffer);
  } catch (err) {
    console.error('Export artifact error:', err);
    res.status(500).json({ error: 'Failed to export artifact' });
  }
});

export default router;
